# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "LBFGS++: A Header-only C++ Library for L-BFGS and L-BFGS-B Algorithms"
email: yixuan.qiu@cos.name
description: A Header-only C++ Library for L-BFGS and L-BFGS-B Algorithms

# Build settings
markdown: kramdown
highlighter: rouge
